### ISSUE TITLE
RZ/G Starter Kit を起動後 3 時間以上使えない

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/gecko-embedded#11]
RZ/G1E & RZ/G1M の Starter Kit は評価ボードという事でドライバも評価版らしく起動後 3 時間で終了してしまう制限がある。

見逃してしまうが次のようなブートログがさりげなく表示されている

> boot:Thu Aug 25 01:46:22 2016: NOTE: This SGX library has the time limitation by reason of an evaluation module.

**Comment by ashie** [comment]
iWaveのRZ/G1Mのボードについてきたドライバは、3時間の制限は無いようだ。

**Comment by dynamis** [comment]
Starter Kit 付属ドライバのライセンスによるもので解決できないだろうから wontfix で close しておく

iWave など製品側では勿論ちゃんとドライバ買ってるとか違うんですかね…
