### ISSUE TITLE
9 月末あたりにミートアップイベント開催

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/gecko-embedded#12]
7 月末に初回のミートアップをしてから少し空いてしまいましたが、2 ヶ月ぶりくらいでコミュニティミートアップをしましょう！

比較的集まりやすい人が多そうな、平日水曜日夜に 1.5 ~ 2 時間程度を想定しています。例えばこんな感じですが如何でしょう？

* https://mozilla.doorkeeper.jp/events/52459
* 日時: 9/28 (水) 19:00 ~ 21:00
* 場所: Mozilla Japan オフィス
* 内容:
  * プロジェクトアップデート by dynamis
  * Wayland サポートの進捗 by 足永さん
  * 96Boards で動かしてみた by 深海さん
  * ディスカッションタイム (今度こそ QA だけじゃなくて...)

**Comment by dynamis** [comment]
TODO:
- [ ] 日時と講師を確定
- [ ] Doorkeeper にイベントページを作成
- [ ] Doorkeeper (mozilla/firefox) などで告知
- [ ] 一部企業の方に個別にご案内

**Comment by naobsd** [comment]
@dynamis ひとまず9/28 19:00～は大丈夫です。

内容は、96Boards HiKeyで動かしてみた、くらいで... (移植らしいことは現状していないので...)

**Comment by naobsd** [comment]
DragonBoard 410cも入手しましたので、これについても少しお話ができればと思います。

**Comment by dynamis** [comment]
こちらに書いてませんでしたが @Hidetaro7 @tommmmmmmmy と #10 についてもお話ししたりコミュニティ的にやりたいこととかフィードバックとかもらうのも含めています

**Comment by dynamis** [comment]
DONE. Thanks!
