### ISSUE TITLE
Graphene のビルド

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/gecko-embedded#23]
Firefox ブラウザの UI などなしで Gecko エンジン上で直接 HTML コンテンツをロードするデスクトップランタイム Graphene をビルドして利用できるようにする。Firefox/Gecko の移植としては Firefox ブラウザで良いが、実際の組み込み製品では Graphene のようなビルドの方が理論上は望ましくなるため。

see: https://mykzilla.org/2016/08/30/graphene-on-gecko-without-b2g/

**Comment by dynamis** [comment]
Building Graphene (Gecko flavor)
https://github.com/browserhtml/browserhtml/wiki/Building-Graphene-%28Gecko-flavor%29
graphene-gecko repo
https://github.com/mykmelez/graphene-gecko

**Comment by dynamis** [comment]
Graphene プロジェクトの開発は 2017 年の開発プライオリティ対象にならなかったようなので GEM としては忘れる。状況が変われば reopen するが一旦 close します。

**Comment by ashie** [comment]
GrapheneをESR52に移植してみたので、以下に置いておく。

https://github.com/mozilla-japan/gecko-dev/tree/esr52-graphene
