### ISSUE TITLE
ONVIF 対応

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/gecko-embedded#37]
ネットワークカメラの標準である ONVIF に対応すると監視カメラのコントローラーや家庭用デバイスからのカメラの映像確認などの機能が簡単に実現できる。

ONFIV Spec はこちら:
http://www.onvif.org/specs/DocMap-16.06.html

**Comment by dynamis** [comment]
少しメモを書き残した:
https://github.com/mozilla-japan/gecko-embedded/wiki/references

**Comment by ashie** [comment]
当面、本件の作業予定は無くなっているのでいったんクローズします。
