### ISSUE TITLE
gem-tanzaniteデモ用レシピ作成

### ISSUE THREAD

**Issue by ashie** [mozilla-japan/gecko-embedded#40]
ルネサスRZ/Gシリーズで[gem-tanzanite](https://github.com/gem-tanzanite/gem-tanzanite.github.io) を用いたデモを行うために手元でSDブートイメージを作成して使用しているが、現状ではレシピだけでは同環境を再現することができず、手動での設定も必要となっている。

[meta-rzg-demos](https://github.com/renesas-rz/meta-rzg-demos)と同様に、bitbake一発でデモ環境を構築できるようにレシピを整備する。

**Comment by ashie** [comment]
#20 で作成するレシピ (https://github.com/mozilla-japan/meta-gecko-embedded) 内にデモ用のレイヤを入れる予定。

**Comment by ashie** [comment]
TODO

* [ ] westonに`--idle-time=0`オプションを付ける
* [ ] 動画関連カーネルモジュールのロード（最新のmeta-renesasに入っているmm-init）
* [ ] gem-tanzaniteのレシピ追加
* [ ] Firefoxの起動アイコン or 自動起動
* [ ] 小さい画面の場合にフルスクリーンで起動できないことがある問題の対応

**Comment by ashie** [comment]
> westonに--idle-time=0オプションを付ける（最新のmeta-renesasには入っている）

現在のmeta-gecko-embeddedと最新のmeta-renesasの組み合わせで動くようなので、特に対応の必要なし。

**Comment by ashie** [comment]
> 動画関連カーネルモジュールのロード（最新のmeta-renesasに入っているmm-init）

Yocto-1.6、2.0のどちらも、最新版ではデフォルトで組み込まれているので特に対応の必要は無し。

**Comment by ashie** [comment]
> 小さい画面の場合にフルスクリーンで起動できないことがある問題の対応

に関しては

> 専用プロファイル

xulstore.jsonに`"sizemode": "fullscreen"`を入れておくことで対処する。

**Comment by ashie** [comment]
> Firefoxでタッチイベントのデフォルト有効化 (firefoxへのパッチ)

ad-hoc過ぎて扱いに困っていたのでどこにも入れてなかったが、

> 専用プロファイル

これと組み合わせて有効化できるようにして各ブランチに入れた。

APZを有効化できるようになればデフォルトでタッチイベントは有効化されるので、
いずれこんなパッチは不要になるはず。

**Comment by ashie** [comment]
> 専用プロファイル
> gem-tanzaniteのレシピ追加

レシピを投入した:

https://github.com/mozilla-japan/meta-gecko-embedded/commit/9448703a6a71906e20db9ab061bdf83a0a280e0b

**Comment by cosmo0920** [comment]
ESR52でe10sを有効化してもクラッシュしなくなるパッチ https://bugzilla.redhat.com/attachment.cgi?id=1287203&action=diff を投入してもabout:xxx以外は開けない、という結果になったので



>> Firefoxでタッチイベントのデフォルト有効化 (firefoxへのパッチ)

> ad-hoc過ぎて扱いに困っていたのでどこにも入れてなかった

このパッチはESR52では必要そうです。

**Comment by ashie** [comment]
> Firefoxの起動アイコン or 自動起動

initスクリプトのレシピを追加（gem-tanzanite-init）
あとはcore-image-gem-tanzaniteとかも追加しておいた方が親切か?

**Comment by ashie** [comment]
> あとはcore-image-gem-tanzaniteとかも追加しておいた方が親切か?

gem-tanzaniteに限らず色々なデモを入れたイメージにしたい。
ということで別に考えるとして、本issueはこれにて終了。

**Comment by ashie** [comment]
ドキュメントが無いので、ビルド手順におまけとして記載しておく。

**Comment by ashie** [comment]
> ドキュメントが無いので、ビルド手順におまけとして記載しておく。

以下に記載した: 

https://github.com/mozilla-japan/meta-browser/wiki/Build-RainboW-G20D-Q7
