### ISSUE TITLE
タブのコンテキストメニューの内容が表示されないことがある

### ISSUE THREAD

**Issue by ashie** [mozilla-japan/gecko-embedded#48]
Wayland版Firefox 52 on Yocto 2.0（GTK+-3.20に更新）でポップアップメニュー類は概ね動作するようになったが、タブのコンテキストメニューが表示されないことがある。厳密な再現条件は不明。

**Comment by cosmo0920** [comment]
これはコンテキストメニュー全般的で表示させるタイミングによってグレーのまま内容が描画されないという問題のようです。

**Comment by ashie** [comment]
#49 と同じ問題では? と思うのでクローズしておきます
